### ISSUE TITLE
 in sites/within, get 500 error when &maxResults parameter not provided

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#20] opened 2016-08-16 00:21 UTC
Example request:

```
http://apps.gov.bc.ca/pub/geocoder/sites/within.json?bbox=-119.8262258460595%2C50.43898650245398%2C-119.750518300591%2C50.46708512083551
```

**Comment by cmhodgson** [comment] 2016-09-12 18:41
The problem is not to do with maxResults, it is that there is a "bad" site somewhere in the list and a small enough maxResults doesn't include that "bad" site. I think this problem is already fixed by newer code in 2.1.2.

**Comment by cmhodgson** [comment] 2016-09-14 16:42
The "bad" site was "0 Back Rd, Westwold, BC" - the range stretching code in the address range generator was accidentally un-stretching the short end of the range for this segment from 0-0 to 2-98. I've fixed this in the range gen code, but the data will need to be re-processed from at least the range-gen point in order to see this fix.

**Comment by cmhodgson** [comment] 2016-09-16 23:22
Confirmed fixed in delivery.

**Comment by mraross** [comment] 2016-09-17 00:50
Verified in delivery using the following request:

http://delivery.apps.gov.bc.ca/pub/geocoder/sites/within.json?bbox=-119.8262258460595%2C50.43898650245398%2C-119.750518300591%2C50.46708512083551

**Comment by mraross** [comment] 2016-10-21 21:55
Verified in test

**Closed** 2016-11-10 23:53 UTC
Labels: api, bug, GEOCODER, high priority
