### ISSUE TITLE
In route planner, change how route not found is handled

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#64] opened 2016-10-03 23:40 UTC
Currently, the router returns an HTTP response code of 400 or 504. Instead,  return an HTTP response code of 200 and a boolean property called routeFound which should be used by clients to determine if a route was found.

The following request is for the shortest route between Nanaimo and Newcastle Island for which there is no route as there is no vehicle ferry between the two islands: 

https://routertst.api.gov.bc.ca/route.kml?routeDescription=Trip%20to%20an%20island%20with%20only%20a%20passenger%20ferry&points=-123.707942%2C48.778691%2C-123.9255472245603%2C49.17704747833908&outputSRS=4326&criteria=shortest&distanceUnit=km&apikey=apikey

**Comment by cmhodgson** [comment] 2016-10-04 00:22
If you change the outputformat to html you can see that it quickly identifies the lack of route. The problem is in the error handling code trying to tell you this in KML format.

**Comment by mraross** [comment] 2016-10-04 16:58
Still getting 504 timeout with html:

https://routertst.api.gov.bc.ca/route.html?routeDescription=Trip%20to%20an%20island%20with%20only%20a%20passenger%20ferry&points=-123.707942%2C48.778691%2C-123.9255472245603%2C49.17704747833908&outputSRS=4326&criteria=shortest&distanceUnit=km&apikey=a82472ff8f754968b4e70943adc63888

**Comment by mraross** [comment] 2016-10-04 16:59
urls above need a valid api key

**Comment by cmhodgson** [comment] 2017-01-09 18:45
The html link above works fine for me on prod/tst/dlv but not if you switch it to .kml - there is something wrong with the KML error handling for at least this case.

**Comment by mraross** [comment] 2017-01-24 19:12
I don't think disconnected points should be treated as a bug. They should be treated as a value route that takes forever. This is similar to the way the no-match case is resolved in the geocoder (e.g., by returning a matchPrecision of Province).

**Comment by cmhodgson** [comment] 2017-01-24 19:49
It is not treated as a bug. Internally, the graphhopper code which does the route finding throws an exception in the case when "no route exists". This issue is about fixing handling of this exception for the the KML outputformat. It is not about changing what should be returned to the user in "no route exists" situation as is proposed by #129 - however this must be fixed in order for changes for changes related to #129 to work when the output format is KML.

**Comment by mraross** [comment] 2017-01-25 19:04
How about adding a routeExists boolean property to the routing results?. routeExists = true if there exists a route that connects all start and stop points; false otherwise. I suggest that when routeExists = false set distance to 60,000,000 and time to 1,000,000 hours so that applications not aware of the possibility a route doesn't exist might still work without a code change (e.g., ACDF).

**Comment by mraross** [comment] 2017-04-25 02:39
Duplicate of issue

**Closed** 2017-04-25 03:18 UTC
Labels: api, enhancement, medium priority, ROUTE PLANNER
